# Generated by Django 4.2 on 2023-05-09 17:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subscribers',
            field=models.ManyToManyField(default=None, related_name='subscribing_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
